apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: cHJpeWVzaHJhaQ==  # base64 for "priyeshrai"
  mongo-root-password: bW9uZ29wYXNz      # base64 for "mongopass"
