# nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment-priyesh
  labels:
    app: my-nginxpriyeshdilli
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginxpriyeshdilli
  template:
    metadata:
      labels:
        app: my-nginxpriyeshdilli
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
